### ISSUE TITLE
Issueで議論をするのだ！練習用Issue

### ISSUE THREAD

**Issue by topstar0624** [prex-inc/webclap#2]
#1 なんだこの番号
**ぼーるど！**
_いたりっく_
> 引用やで～
`インラインのCode` やで
[URLも貼れるんやで](http://pr.hoshisaki.net/)

- リスト
- だよ

- [ ] チェックボックスでTODO管理もできるの？
- [x] 終わったらxを入れるんやで 

@s-ikeda141104 メンションめんしょん
@prex-inc/laravel チームごとにメンション飛ばせるらしいよ

**Comment by topstar0624** [comment]
![kaeru](https://cloud.githubusercontent.com/assets/17560001/20710638/af3f7146-b67e-11e6-9ee9-b5295360cec9.jpg)

キータみたいに画像も貼り付けできるお

**Comment by topstar0624** [comment]
issueを閉じるぞよ

**Comment by s-ikeda141104** [comment]
なるほどなるほど

**Comment by topstar0624** [comment]
![寿司ゆき:yes](https://d1zd1v0cxnbx2w.cloudfront.net/images/sets/sushiyuki/01.png) 

![ミサワ](https://d20qqtosks8wga.cloudfront.net/1/2/126717ae-s.gif)

**Comment by topstar0624** [comment]
Chrome拡張機能のLTTM素敵！
